### ISSUE TITLE
Tool Tips

### ISSUE THREAD

**Issue by another4til7** [Sigil-Ebook/PageEdit#16]
The app does not have a help item and the various icons do not have tooltips. Please add tools tips and, if there's a manual of some kind, please link it from the app or at least put an entry in the README.md so people can find it.

**Comment by dougmassay** [comment]
Every icon in Sigil has a tooltip. And there are links to the user manual in the wiki (and the user manual itself is in the traditional '"Docs" folder.

**Comment by kevinhendricks** [comment]
Yes PageEdit does have tooltips.  Simply hover over an icon to see its function.  These icons generally match those in Sigil as PageEdit was designed to be a companion program to Sigil to be launched via Sigil's External XHTML Editor icon (as set with Sigil Preferences).
