### ISSUE TITLE
No source code mode

### ISSUE THREAD

**Issue by another4til7** [Sigil-Ebook/PageEdit#17]
The first file I attempted to open, an ePub file generated by wictionary, shows an error (PCData invalid character at) without indicating what page throws the error and (more importantly) not offering a edit source button. 

When I use my old copy of Sigil, it is able to read the file _and_ offers a source code view :-/

**Comment by dougmassay** [comment]
I have no idea what you mean by "source code view". Code View is prominently displayed where it always was. It's "Book View" that has been removed. You should probably stick with your old version of Sigil if it works for what you want to do.

**Comment by kevinhendricks** [comment]
In PageEdit, you can use the Inspector to see and edit the Source Code.  PageEdit is typically used by making it an External XHTML Editor in Sigil's Preferences.q

**Comment by dougmassay** [comment]
> The first file I attempted to open, an ePub file generated by wictionary

That was your mistake. PageEdit can't open epub files. Mainly because it's not an epub editor. It's primarily a wysiwyg xhtml file editor.
