### ISSUE TITLE
Set case buttons missing

### ISSUE THREAD

**Issue by Rukbat16** [Sigil-Ebook/PageEdit#18]
I cannot seem to find any command within PageEdit to automatically modify the case of strings of letters, either in the bar or in the menus.
While I am using PageEdit from within Sigil, content changes are only ported from PageEdit to Sigil and not vice versa, so it would be useful to have set case buttons in PageEdit as well.

**Comment by kevinhendricks** [comment]
Why not handle casing changes in Sigil before launching PageEdit for final proofing?  PageEdit really should not need to duplicate all of the editing features available in Sigil.

We will take this feature request under consideration for a future release but no promises.

**Comment by kevinhendricks** [comment]
Why not handle casing changes in Sigil before launching PageEdit for final proofing?  PageEdit really should not need to duplicate all of the editing features available in Sigil.

We will take this feature request under consideration for a future release but no promises.

**Comment by kevinhendricks** [comment]
Why not handle casing changes in Sigil before launching PageEdit for final proofing?  PageEdit really should not need to duplicate all of the editing features available in Sigil.

We will take this feature request under consideration for a future release but no promises.

**Comment by Rukbat16** [comment]
I thought PageEdit was meant to be an editor, not just a "final proofing" tool. Isn't that what the preview window is for?

**Comment by kevinhendricks** [comment]
PageEdit is meant to be a final proofing tool with the ability to do simple visual editing.  It can not be used to add new images, xhtml, etc to an epub as these are reserved for Sigil.

Preview in Sigil does help but the interface is a bit much for proofing and final touchups.  When you launch PageEdit from Sigil as the Preferred External Editor when CodeView shows the OPF, it makes final touchups during reading easy.

**Comment by kevinhendricks** [comment]
The case changing functionality has been added to PageEdit with the most recent commit to master.  That feature will appear in the next release.

Closing this feature request.
