### ISSUE TITLE
"Add to dictionary" option in context menu?

### ISSUE THREAD

**Issue by minibug1021** [Sigil-Ebook/PageEdit#19]
I work a lot with OCR rendered text that's in a mix of primarily English with things like the names of corporations in other languages, like French or Spanish. Lots of times I will end up with big blocks of names that are underlined red where I have to manually look over each word to make sure it's the correct spelling, whereas if I could add the correct spelling to dictionary with the right-click context menu it would only highlight words that I know to be spelled incorrectly.

**Comment by kevinhendricks** [comment]
Sorry but spellchecking and dictionary support is completely determined by Qt's QWebEngine (Chrome-based) spell checking and binary converted Hunspell Dictionaries with no support for adding words on the fly.

If you want that capability use Sigil which already supports that and more.

If you want support of user based dictionaries and word lists in Chrome please file a issue report with them requesting this feature.

Closing this as not a feature PageEdit controls.
