### ISSUE TITLE
possible non-free (but unused) js file

### ISSUE THREAD

**Issue by mapreri** [Sigil-Ebook/PageEdit#21]
Hi,

during a copyright review of this project, we have noticed that `javascript/jquery.wrapSelection.js` doesn't mention any specific license.  Googling around a bit, it seems that the former project page might have been https://web.archive.org/web/20080913031556/http://plugins.jquery.com/project/wrapSelection - but that also doesn't mention any specific license.

I'm afraid that assuming the license to be the same as the whole PageEdit project is not really feasible in this case.

The good part is that we couldn't find any reference to that file anywhere else in the code, so I believe it might be simply possible to just remove that file from the sources.  Could you please confirm that it's indeed not used anywhere and could be removed?

Incidentally, this file is also present in the Sigil sources, likewise not mentioned anywhere.

**Comment by kevinhendricks** [comment]
Yes, this appears to have been unused for quite some time as it was back in the Sigil 0.4 and Sigil 0.5 days when they tried to implement undo for Find and Replace in BookView.  As far as I can tell it used to be used by the replace_wrapped.js which was gone in Sigil 0.6.0.

Yes it can be removed.  I will remove it from both PageEdit and Sigil sources along with the obsolete version of jquery-1.6, sometime tomorrow when I get back to a desktop machine.

Thanks for the head's up.

**Comment by kevinhendricks** [comment]
Removed.  Closing this.
