### ISSUE TITLE
VERTICAL ALIGN? Is there available in this editor?

### ISSUE THREAD

**Issue by kalxn** [Sigil-Ebook/PageEdit#23]
Hi, I'm begging to understand how to vertical-align properly a set of lines, or one line. I tried the margin top and bottom and width, and it's kind off the center. I tried grid and placement of items and it won't vertically align item. Is there any ways things can be vertically aligned in PageEdit? Sorry for asking guys.

**Comment by eli-schwartz** [comment]
Asking is fine, but shouldn't you be asking on the actual user support forums at https://mobileread.com rather than submitting an error report on github?

**Comment by kalxn** [comment]
Okay. Now I know. Thank You.
