### ISSUE TITLE
Check spelling in PageEdit

### ISSUE THREAD

**Issue by webghostx** [Sigil-Ebook/PageEdit#24]
I am new to Sigil. I think the idea is very good. But working in the source code distracts too much from writing. So PageEdit is a great addition. But there is one thing I miss, the spell check.

So I have to go back to the Sigil source code to use the spell checker. Have I missed something, is there a way to activate the spell check directly in PageEdit?

**Comment by kevinhendricks** [comment]
PageEdit can spellcheck but only in the dictionaries that have been processed into Chrome's binary dictionary format.  Windows and Mac builds of PageEdit come with a few dictionaries included.   This spellcheck support is limited.  Simply check the PageEdit menus.

PageEdit was designed to be launched from within Sigil via an External Xhtml Editor icon primarily for proof reading.  So Sigil's own spellcheck can be used before launch typically quite easily.

Note, if launched from within Sigil when the opf is open, all xhtml files listed in the opf file will be available for editing.

**Comment by webghostx** [comment]
Okay thank you. i work on ubuntu. Are there other restrictions?

I can't find any opf files either. I only have the epub and the xhtml inside it. Now I have found the folder 'dictionaries' and am even more confused. Because I can't find anything in the menu

Version: 1.4.0
Builddatum: Dec 11 2020
Buildzeit: 10:23:16
Qt-Laufzeitversion: 5.12.8
Qt-Buildversion: 5.12.8
System: Ubuntu 20.04.1 LTS
Architektur: x86_64

**Comment by kevinhendricks** [comment]
In Sigil, use Preferences to set PageEdit as your Preferred XHTML editor.  Then open the epub in Sigil , in Sigil's BookBrowser double click in the .opf file to open it.  Then launch the Preferred XHTML editor using the icon or menu.

Alternatively,  you can use unzip on your .epub file to open it.
Inside of that folder look for the .opf file.  That is the file you want to navigate to and open with PageEdit to get all of the xhtml files at once.

In PageEdits file open dialog, you should be able to set your file filter to .opf  to see and open it.

I have no idea if ubuntu installs the dictionaries or not.  They must be binary files processed by chrome.  Check with your distribution maintainer for additional packages that might have what you want.

**Comment by webghostx** [comment]
Thank you. Now I see the problem. The spell check would be there, but I can't select a dictionary. The selection is empty.

I have to look how I can fix this
![pageEdit](https://user-images.githubusercontent.com/5307244/102529194-dad06400-409f-11eb-8b99-ca359dad2ecb.jpg)
