### ISSUE TITLE
Adding dictionaries in Persian or Arabic

### ISSUE THREAD

**Issue by foaad1961** [Sigil-Ebook/PageEdit#27]
Please forgive my ignorance. This is a request. Is it possible to add dictionaries in other languages to PageEdit? 
Thank you,
Foaad Haghighi

**Comment by kevinhendricks** [comment]
It is possible to use a Google Chromium / Qt tool to process a Hunspell dictionary to the required binary format. So if a Hunspell dictionary exists for your target language, then you could manually convert it add the binary file beside the other dictionaries.

**Comment by kevinhendricks** [comment]
The Qt program is called:

qwebengine_convert_dict

and it converts hunspell dictionaries to .bdic formats.

Hope this helps.

**Comment by foaad1961** [comment]
Kevin,
Thank you so much. This suggestion helps a lot, as I have done the same for Adobe Indesign.
Best
