### ISSUE TITLE
Approval request to implement package manager and Command Palette in PageEdit

### ISSUE THREAD

**Issue by livrasand** [Sigil-Ebook/PageEdit#34]
Dear PageEdit Development Team,

I hope this message finds you well. I am writing to you as a developer interested in contributing to the PageEdit project. I've been using PageEdit for a while and have identified an opportunity to improve the user experience by allowing developers to create and share Plugins through a dedicated Package Manager. Additionally, I propose the implementation of a Command Palette to facilitate the installation, search, uninstallation and removal of Plugins within the application.

The main objective of these additions is to foster the development community by providing a more accessible and friendly platform for the expansion of functionality through Plugins. Likewise, it would contribute to making PageEdit an even more versatile tool and adaptable to the individual needs of users.

Below, I briefly break down the key points of the proposals:

- **Package Manager for Plugins:** This component would allow developers to upload their Plugins to a centralized repository, from where users could easily explore, install and update available Plugins.

- **Command Palette:** I would introduce a Command Palette to the PageEdit user interface, offering users a quick and efficient way to manage installed Plugins, as well as search and discover new Plugins.

Before embarking on this project and dedicating time and resources to its development, I would like to formally request your approval to carry out these modifications and additions within the corresponding legal framework. I understand the importance of following established procedures and ensuring that any changes made to the PageEdit project comply with the guidelines and policies established by the development team.

I am fully committed to working closely with you throughout the implementation process, ensuring that the proposed modifications integrate harmoniously and coherently with the overall vision of the PageEdit project.

I sincerely appreciate your consideration and look forward to the opportunity to contribute positively to the continued development of PageEdit. I remain at your disposal for any additional questions, comments or suggestions you may have regarding this proposal.

Sincerely,
Livrädo Sandoval.

**Comment by kevinhendricks** [comment]
PageEdit is an helper tool to the Sigil application it sprang from.  Sigil has an interface to easy launch and work with PageEdit.  Sigil already has a full python3 based plugin system and already has a collection of epub related plugins that users have contributed.

So we would have very very little interest in duplicating the plugin functionality in PageEdit itself.

Sorry.
