### ISSUE TITLE
Suggest adding a one click pop-up explanatory note function

### ISSUE THREAD

**Issue by lvluozixuemengyanyan** [Sigil-Ebook/PageEdit#40]
Sometimes it is necessary to add some annotations to a sentence in a book，so，Suggest adding a one click pop-up explanatory note function

**Comment by dougmassay** [comment]
Not sure what to say here. It would seem to me that a pop-up footnote/annotation would be a feature of an epub _reader_, not a wysiwyg xhtml editor. If you need to edit something other than text, then Sigil or another xhtml editor is what you want. PageEdit was made for wysiwyg text editing.

**Comment by kevinhendricks** [comment]
Agreed.  And, any suggestiins for new features should be made on iur Mobileread user forum and not here.

Closing this.
