### ISSUE TITLE
word counter

### ISSUE THREAD

**Issue by losangesable** [Sigil-Ebook/PageEdit#41]
I use Sigil and PageEdit to write short stories and would appreciate a word counter. Thanks.

**Comment by kevinhendricks** [comment]
Then make any request for new features on Mobileread.com Sigil User's Forum so that interested users can comment.

Not here.  This is for actual bug reports.

**Comment by dougmassay** [comment]
Also note that although people are certainly free to use Sigil/PageEdit in any way they see fit, we did not design (nor recommend) them as authorial tools. Authorial features will likely be a hard sell because of that.

**Comment by losangesable** [comment]
> Also note that although people are certainly free to use Sigil/PageEdit in any way they see fit, we did not design (nor recommend) them as authorial tools. Authorial features will likely be a hard sell because of that.

It's extra work to copy and paste into another tool. And PageEdit is just a text editor. But thanks for your interest in improving the tool.

**Comment by losangesable** [comment]
> Then make any request for new features on Mobileread.com Sigil User's Forum so that interested users can comment.
> 
> Not here. This is for actual bug reports.

Sorry.

**Comment by dougmassay** [comment]
> It's extra work to copy and paste into another tool. 

There's enough import plugins for Sigil that work with full-featured authorial tools that copying and pasting is rarely required.

> And PageEdit is just a text editor.

That's sort of the point. It's just a text editor. And not one with a ton of handy features. Hence your desire for it to incorporate features that other common authorial tools already have at their disposal. Copying things that word processing programs already do (and much better) was never our intention for PageEdit.

**Comment by losangesable** [comment]
Sorry, I see I haven't explained myself correctly.

I don't use Sigil/PageEdit as an authoring tool.

I have my own way of writing my short stories: NotePad. No distractions.

Although it may seem incredible, it's all I need to write my short stories in the Spanish way (between 3 and 10 pages).

Then I package my story in Sigil. But in PageEdit I do make last-minute corrections. And that's when I miss a quick word counter.

I understand what you're saying. I'll look into those import add-ons. In the search function to count words (Ctrl+Alt+N) in Sigil I can't find anything. In Reports, I do see it. Although it doesn't count the same as Word... ;-) it's fine for me. I'll look into why the difference exists.

Thank you very much for your interest in my need.

**Comment by kevinhendricks** [comment]
You must put in the proper regex to tell it what to count.  Off the top of my head, something like:

\w+\b

Which should detect a sequence of word characters followed by a non-word character boundary.

Yes, what sequence of characters constitutes a "word" for the purposes of word counts  is subject to debate.

**Comment by losangesable** [comment]
I'll leave it here for anyone who might be interested: in the translation of Sigil into Spanish, the word counter is in Herramientas (Tools?) > Informes (Reports?) … Archivos HTML (Files HTML?).

Thank you both very much for your help and understanding.

**Comment by losangesable** [comment]
Thank you, friends:

**Sigil-2.4.0
   New Features
     - added a GetInfo dialog and right click menu option for XHTML files that provides a collection
         of information specific to that file without having to run Reports (including a word count)**
