### ISSUE TITLE
Can't install it on ubuntu 19.10

### ISSUE THREAD

**Issue by kailor** [Sigil-Ebook/PageEdit#7]
There isn't any way to install in on ubuntu. 

Please write step-by-step details on how to install it.

**Comment by dougmassay** [comment]
Use the repo version of Sigil if you need that level of help. Otherwise, There are detailed install/build instructions in the docs folder. Please don't use the issue database as a help desk. The Mobileread forums are where to go for support.

**Comment by dougmassay** [comment]
Sorry. I assumed Sigil before I saw it was PageEdit. We do need some documentation updates, but the general idea is the same as Sigil.  cmake, make, make install.
