### ISSUE TITLE
Hyperlinks: No easy way to follow or check destination

### ISSUE THREAD

**Issue by rodneylives** [Sigil-Ebook/PageEdit#9]
There is no way to check the destination of a placed link except to select part of it and choose Insert Link. It was easier to check destination/follow links in older Sigil. It would be useful if a link's destination appeared on the status line when hovering over it, and if ctrl-click opened external links in the system browser.

**Comment by dougmassay** [comment]
If you're using PageEdit from within Sigil as an external editor, open the OPF file and make sure the Edit/Preview toggle button is set to Preview. That way you'll be able to follow/verify all of the books internal links. Switch back to Edit mode when you want to make a change.

If you've opened a single xhtml file in PageEdit, switching to Preview mode will cause links another page in the book to be opened in a browser.

PageEdit doesn't have a status line.

This is all as it's intended to be.

**Comment by rodneylives** [comment]
Ah! I was looking at the line with the zoom slider as a status line. Thanks for info, will try this!

**Comment by dougmassay** [comment]
No problem. Best to open the opf file and use it that way, though. Opening a link with an external browser doesn't always work on all platforms. Qt makes it very difficult to open a local file in an external web browser for some reason.

**Comment by kevinhendricks** [comment]
Closing.
